-- Purpose: Verify ACCT_REPORT_ENGINE_V1 package compile fix.

SET SERVEROUTPUT ON;

DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(1)
      INTO v_count
      FROM USER_OBJECTS
     WHERE OBJECT_NAME = 'ACCT_REPORT_ENGINE_V1'
       AND OBJECT_TYPE IN ('PACKAGE', 'PACKAGE BODY')
       AND STATUS = 'INVALID';

    IF v_count > 0 THEN
        RAISE_APPLICATION_ERROR(-20905, 'ACCT_REPORT_ENGINE_V1 remains INVALID - check USER_ERRORS');
    END IF;

    SELECT COUNT(1)
      INTO v_count
      FROM USER_PROCEDURES
     WHERE OBJECT_NAME = 'ACCT_REPORT_ENGINE_V1'
       AND PROCEDURE_NAME = 'NETAMOUNT';

    IF v_count = 0 THEN
        RAISE_APPLICATION_ERROR(-20905, 'ACCT_REPORT_ENGINE_V1.NETAMOUNT is not exposed');
    END IF;

    DBMS_OUTPUT.PUT_LINE('OK: ACCT_REPORT_ENGINE_V1 package compile fix is valid');
END;
/