-- Purpose: Validate Oracle Text execution plan and index health for jurnal keyword search.
-- Date: 2026-03-18

DEFINE P_IDDATA = 'SAMPLE_IDDATA';
DEFINE P_PERIODE = '03/2026';
DEFINE P_NOJURNAL = 'JU/2026/001';
DEFINE P_KETERANGAN = 'pemupukan kebun';

ALTER SESSION SET NLS_DATE_FORMAT = 'YYYY-MM-DD';

PROMPT === Oracle Text Index Status ===
SELECT INDEX_NAME, INDEX_TYPE, STATUS
  FROM USER_INDEXES
 WHERE INDEX_NAME IN ('IDX_CTX_ACCT_JD_NOJURNAL', 'IDX_CTX_ACCT_JD_KETERANGAN')
 ORDER BY INDEX_NAME;

SELECT IDX_NAME, IDX_STATUS, IDX_SYNC_TYPE
  FROM CTXSYS.CTX_USER_INDEXES
 WHERE IDX_NAME IN ('IDX_CTX_ACCT_JD_NOJURNAL', 'IDX_CTX_ACCT_JD_KETERANGAN')
 ORDER BY IDX_NAME;

PROMPT === Plan: Oracle Text NOJURNAL ===
EXPLAIN PLAN SET STATEMENT_ID = 'QCTX_NOJURNAL' FOR
SELECT REFFID, HIDREFF, NOJURNAL, TANGGAL, BARIS, KODE, REKENING, DEBET, KREDIT, KETERANGAN, POSTED, PERIODE
  FROM ACCT_JURNAL_DTL
 WHERE IDDATA = '&P_IDDATA'
   AND PERIODE = '&P_PERIODE'
   AND CONTAINS(NOJURNAL, '%' || LOWER('&P_NOJURNAL') || '%') > 0
 ORDER BY NOJURNAL, BARIS;

SELECT *
  FROM TABLE(DBMS_XPLAN.DISPLAY('PLAN_TABLE', 'QCTX_NOJURNAL', 'BASIC +PREDICATE +COST +ROWS'));

PROMPT === Plan: Oracle Text KETERANGAN ===
EXPLAIN PLAN SET STATEMENT_ID = 'QCTX_KETERANGAN' FOR
SELECT REFFID, HIDREFF, NOJURNAL, TANGGAL, BARIS, KODE, REKENING, DEBET, KREDIT, KETERANGAN, POSTED, PERIODE
  FROM ACCT_JURNAL_DTL
 WHERE IDDATA = '&P_IDDATA'
   AND PERIODE = '&P_PERIODE'
   AND CONTAINS(KETERANGAN, '%' || LOWER('&P_KETERANGAN') || '%') > 0
 ORDER BY NOJURNAL, BARIS;

SELECT *
  FROM TABLE(DBMS_XPLAN.DISPLAY('PLAN_TABLE', 'QCTX_KETERANGAN', 'BASIC +PREDICATE +COST +ROWS'));

PROMPT === Plan: Legacy LIKE (Baseline Compare) ===
EXPLAIN PLAN SET STATEMENT_ID = 'QLIKE_COMPARE' FOR
SELECT REFFID, HIDREFF, NOJURNAL, TANGGAL, BARIS, KODE, REKENING, DEBET, KREDIT, KETERANGAN, POSTED, PERIODE
  FROM ACCT_JURNAL_DTL
 WHERE IDDATA = '&P_IDDATA'
   AND PERIODE = '&P_PERIODE'
   AND (LOWER(NOJURNAL) LIKE '%' || LOWER('&P_NOJURNAL') || '%'
        OR LOWER(KETERANGAN) LIKE '%' || LOWER('&P_KETERANGAN') || '%')
 ORDER BY NOJURNAL, BARIS;

SELECT *
  FROM TABLE(DBMS_XPLAN.DISPLAY('PLAN_TABLE', 'QLIKE_COMPARE', 'BASIC +PREDICATE +COST +ROWS'));
