-- Purpose: Rollback per-job impacted-account table.
-- Date: 2026-06-26

SET SERVEROUTPUT ON;

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE ACCT_RECALC_JOB_ACCOUNT CASCADE CONSTRAINTS';
    DBMS_OUTPUT.PUT_LINE('DROPPED TABLE: ACCT_RECALC_JOB_ACCOUNT');
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE = -942 THEN
            DBMS_OUTPUT.PUT_LINE('SKIPPED (missing): ACCT_RECALC_JOB_ACCOUNT');
        ELSE
            RAISE;
        END IF;
END;
/
