-- Purpose: Re-enable legacy COA mutation triggers on ACCT_JURNAL_DTL.
-- Date: 2026-03-20

SET SERVEROUTPUT ON;

BEGIN
    EXECUTE IMMEDIATE 'ALTER TRIGGER UPDATE_COA_FROM_UPDATE ENABLE';
    DBMS_OUTPUT.PUT_LINE('ENABLED TRIGGER: UPDATE_COA_FROM_UPDATE');
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('SKIPPED/ERROR UPDATE_COA_FROM_UPDATE: ' || SQLERRM);
END;
/

BEGIN
    EXECUTE IMMEDIATE 'ALTER TRIGGER UPDATE_COA_FROM_DELETE ENABLE';
    DBMS_OUTPUT.PUT_LINE('ENABLED TRIGGER: UPDATE_COA_FROM_DELETE');
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('SKIPPED/ERROR UPDATE_COA_FROM_DELETE: ' || SQLERRM);
END;
/
