-- Purpose: Rollback server-side recalc drainer (scheduler job + package).
-- Date: 2026-06-26

SET SERVEROUTPUT ON;

DECLARE
    v_count NUMBER := 0;
BEGIN
    SELECT COUNT(1) INTO v_count FROM USER_SCHEDULER_JOBS WHERE JOB_NAME = 'ACCT_RECALC_DRAINER_JOB';
    IF v_count > 0 THEN
        DBMS_SCHEDULER.DROP_JOB(job_name => 'ACCT_RECALC_DRAINER_JOB', force => TRUE);
        DBMS_OUTPUT.PUT_LINE('DROPPED SCHEDULER JOB: ACCT_RECALC_DRAINER_JOB');
    ELSE
        DBMS_OUTPUT.PUT_LINE('SKIPPED (missing): ACCT_RECALC_DRAINER_JOB');
    END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP PACKAGE ACCT_RECALC_DRAINER';
    DBMS_OUTPUT.PUT_LINE('DROPPED PACKAGE: ACCT_RECALC_DRAINER');
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE = -4043 THEN
            DBMS_OUTPUT.PUT_LINE('SKIPPED (missing): ACCT_RECALC_DRAINER');
        ELSE
            RAISE;
        END IF;
END;
/
