-- Purpose: Rollback wrapper package ACCT_RECALLCULATIONS_V2.
-- Date: 2026-03-19

SET SERVEROUTPUT ON;

DECLARE
    v_count NUMBER := 0;
BEGIN
    SELECT COUNT(1)
      INTO v_count
      FROM USER_OBJECTS
     WHERE OBJECT_NAME = 'ACCT_RECALLCULATIONS_V2'
       AND OBJECT_TYPE = 'PACKAGE';

    IF v_count > 0 THEN
        EXECUTE IMMEDIATE 'DROP PACKAGE ACCT_RECALLCULATIONS_V2';
        DBMS_OUTPUT.PUT_LINE('DROPPED PACKAGE ACCT_RECALLCULATIONS_V2');
    ELSE
        DBMS_OUTPUT.PUT_LINE('SKIPPED (not found): PACKAGE ACCT_RECALLCULATIONS_V2');
    END IF;
END;
/
