-- Purpose: Roll back metadata-driven accounting report engine.

DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(1)
      INTO v_count
      FROM USER_OBJECTS
     WHERE OBJECT_NAME = 'ACCT_REPORT_ENGINE_V1'
       AND OBJECT_TYPE = 'PACKAGE';

    IF v_count > 0 THEN
        EXECUTE IMMEDIATE 'DROP PACKAGE ACCT_REPORT_ENGINE_V1';
    END IF;

    SELECT COUNT(1)
      INTO v_count
      FROM USER_TABLES
     WHERE TABLE_NAME = 'ACCT_REPORT_SECTION_ACCOUNT';

    IF v_count > 0 THEN
        EXECUTE IMMEDIATE 'DROP TABLE ACCT_REPORT_SECTION_ACCOUNT PURGE';
    END IF;

    SELECT COUNT(1)
      INTO v_count
      FROM USER_TABLES
     WHERE TABLE_NAME = 'ACCT_REPORT_SECTION';

    IF v_count > 0 THEN
        EXECUTE IMMEDIATE 'DROP TABLE ACCT_REPORT_SECTION PURGE';
    END IF;

    SELECT COUNT(1)
      INTO v_count
      FROM USER_TABLES
     WHERE TABLE_NAME = 'ACCT_REPORT_DEF';

    IF v_count > 0 THEN
        EXECUTE IMMEDIATE 'DROP TABLE ACCT_REPORT_DEF PURGE';
    END IF;

    DBMS_OUTPUT.PUT_LINE('DROPPED ACCT_REPORT_ENGINE_V1 METADATA');
END;
/
