-- Purpose: Drop package ACCT_JURNAL_CLOSING_V2
-- Date: 2026-06-28

DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(1)
      INTO v_count
      FROM USER_OBJECTS
     WHERE OBJECT_NAME = 'ACCT_JURNAL_CLOSING_V2'
       AND OBJECT_TYPE = 'PACKAGE';

    IF v_count > 0 THEN
        EXECUTE IMMEDIATE 'DROP PACKAGE ACCT_JURNAL_CLOSING_V2';
    END IF;

    DBMS_OUTPUT.PUT_LINE('DROPPED ACCT_JURNAL_CLOSING_V2');
END;
/
