-- Purpose: Correct default LABARUGI metadata roots to match ACCT_COA code format.

DECLARE
BEGIN
    EXECUTE IMMEDIATE q'[
UPDATE ACCT_REPORT_SECTION_ACCOUNT account
   SET account.IS_ACTIVE = 'N'
 WHERE account.JENIS_AKUNTING = '*'
   AND account.IDDATA IS NULL
   AND account.TAHUN IS NULL
   AND account.KODEACC_ROOT IN ('4', '5', '6', '7', '8')
   AND account.SECTION_ID IN (
       SELECT section.SECTION_ID
         FROM ACCT_REPORT_SECTION section
        WHERE section.REPORT_CODE = 'LABARUGI'
   )]';

    EXECUTE IMMEDIATE q'[
MERGE INTO ACCT_REPORT_SECTION_ACCOUNT target
USING (
    SELECT section.SECTION_ID, '*' JENIS_AKUNTING, CAST(NULL AS VARCHAR2(20)) IDDATA, CAST(NULL AS NUMBER) TAHUN, '60.00000.000' KODEACC_ROOT, 10 DISPLAY_ORDER
      FROM ACCT_REPORT_SECTION section WHERE section.REPORT_CODE = 'LABARUGI' AND section.SECTION_CODE = 'PENDAPATAN'
    UNION ALL SELECT section.SECTION_ID, '*', NULL, NULL, '61.00000.000', 10 FROM ACCT_REPORT_SECTION section WHERE section.REPORT_CODE = 'LABARUGI' AND section.SECTION_CODE = 'HPP'
    UNION ALL SELECT section.SECTION_ID, '*', NULL, NULL, '70.00000.000', 10 FROM ACCT_REPORT_SECTION section WHERE section.REPORT_CODE = 'LABARUGI' AND section.SECTION_CODE = 'BIAYA_UMUM_ADMIN'
    UNION ALL SELECT section.SECTION_ID, '*', NULL, NULL, '91.00000.000', 10 FROM ACCT_REPORT_SECTION section WHERE section.REPORT_CODE = 'LABARUGI' AND section.SECTION_CODE = 'PENDAPATAN_DILUAR_USAHA'
    UNION ALL SELECT section.SECTION_ID, '*', NULL, NULL, '92.00000.000', 10 FROM ACCT_REPORT_SECTION section WHERE section.REPORT_CODE = 'LABARUGI' AND section.SECTION_CODE = 'PENGELUARAN_DILUAR_USAHA'
    UNION ALL SELECT section.SECTION_ID, '*', NULL, NULL, '80.10000.000', 10 FROM ACCT_REPORT_SECTION section WHERE section.REPORT_CODE = 'LABARUGI' AND section.SECTION_CODE = 'BIAYA_TM'
    UNION ALL SELECT section.SECTION_ID, '*', NULL, NULL, '80.20000.000', 20 FROM ACCT_REPORT_SECTION section WHERE section.REPORT_CODE = 'LABARUGI' AND section.SECTION_CODE = 'BIAYA_TM'
    UNION ALL SELECT section.SECTION_ID, '*', NULL, NULL, '81.10000.000', 30 FROM ACCT_REPORT_SECTION section WHERE section.REPORT_CODE = 'LABARUGI' AND section.SECTION_CODE = 'BIAYA_TM'
    UNION ALL SELECT section.SECTION_ID, '*', NULL, NULL, '81.20000.000', 40 FROM ACCT_REPORT_SECTION section WHERE section.REPORT_CODE = 'LABARUGI' AND section.SECTION_CODE = 'BIAYA_TM'
) source
ON (target.SECTION_ID = source.SECTION_ID
AND target.JENIS_AKUNTING = source.JENIS_AKUNTING
AND NVL(target.IDDATA, '*') = NVL(source.IDDATA, '*')
AND NVL(target.TAHUN, 0) = NVL(source.TAHUN, 0)
AND target.KODEACC_ROOT = source.KODEACC_ROOT)
WHEN MATCHED THEN
    UPDATE SET target.DISPLAY_ORDER = source.DISPLAY_ORDER,
               target.IS_ACTIVE = 'Y'
WHEN NOT MATCHED THEN
    INSERT (SECTION_ID, JENIS_AKUNTING, IDDATA, TAHUN, KODEACC_ROOT, DISPLAY_ORDER)
    VALUES (source.SECTION_ID, source.JENIS_AKUNTING, source.IDDATA, source.TAHUN, source.KODEACC_ROOT, source.DISPLAY_ORDER)]';

    DBMS_OUTPUT.PUT_LINE('CORRECTED LABARUGI DEFAULT COA ROOTS');
END;
/