-- Purpose: Add staging GTT for set-based jurnal detail upsert and durable recalc job table.
-- Date: 2026-03-19

SET SERVEROUTPUT ON;

DECLARE
    PROCEDURE create_table_if_missing(p_table IN VARCHAR2, p_sql IN CLOB) IS
        v_count NUMBER := 0;
    BEGIN
        SELECT COUNT(1)
          INTO v_count
          FROM USER_TABLES
         WHERE TABLE_NAME = UPPER(p_table);

        IF v_count = 0 THEN
            EXECUTE IMMEDIATE p_sql;
            DBMS_OUTPUT.PUT_LINE('CREATED TABLE: ' || UPPER(p_table));
        ELSE
            DBMS_OUTPUT.PUT_LINE('SKIPPED (exists): ' || UPPER(p_table));
        END IF;
    END;

    PROCEDURE create_gtt_if_missing(p_table IN VARCHAR2, p_sql IN CLOB) IS
        v_count NUMBER := 0;
    BEGIN
        SELECT COUNT(1)
          INTO v_count
          FROM USER_TABLES
         WHERE TABLE_NAME = UPPER(p_table);

        IF v_count = 0 THEN
            EXECUTE IMMEDIATE p_sql;
            DBMS_OUTPUT.PUT_LINE('CREATED GTT: ' || UPPER(p_table));
        ELSE
            DBMS_OUTPUT.PUT_LINE('SKIPPED (exists): ' || UPPER(p_table));
        END IF;
    END;

    PROCEDURE create_index_if_missing(p_index_name IN VARCHAR2, p_sql IN CLOB) IS
        v_count NUMBER := 0;
    BEGIN
        SELECT COUNT(1)
          INTO v_count
          FROM USER_INDEXES
         WHERE INDEX_NAME = UPPER(p_index_name);

        IF v_count = 0 THEN
            EXECUTE IMMEDIATE p_sql;
            DBMS_OUTPUT.PUT_LINE('CREATED INDEX: ' || UPPER(p_index_name));
        ELSE
            DBMS_OUTPUT.PUT_LINE('SKIPPED (exists): ' || UPPER(p_index_name));
        END IF;
    END;

    PROCEDURE create_constraint_if_missing(p_table IN VARCHAR2, p_constraint_name IN VARCHAR2, p_sql IN CLOB) IS
        v_count NUMBER := 0;
    BEGIN
        SELECT COUNT(1)
          INTO v_count
          FROM USER_CONSTRAINTS
         WHERE TABLE_NAME = UPPER(p_table)
           AND CONSTRAINT_NAME = UPPER(p_constraint_name);

        IF v_count = 0 THEN
            EXECUTE IMMEDIATE p_sql;
            DBMS_OUTPUT.PUT_LINE('CREATED CONSTRAINT: ' || UPPER(p_constraint_name));
        ELSE
            DBMS_OUTPUT.PUT_LINE('SKIPPED (exists): ' || UPPER(p_constraint_name));
        END IF;
    END;
BEGIN
    create_gtt_if_missing('ACCT_JURNAL_DTL_STAGE_TMP', '
        CREATE GLOBAL TEMPORARY TABLE ACCT_JURNAL_DTL_STAGE_TMP
        (
            SESSION_TOKEN VARCHAR2(64)  NOT NULL,
            BARIS         NUMBER(10)    NOT NULL,
            KODE          VARCHAR2(64)  NULL,
            REKENING      VARCHAR2(512) NULL,
            DEBET         NUMBER(18,2)  NULL,
            KREDIT        NUMBER(18,2)  NULL,
            KETERANGAN    VARCHAR2(512) NULL
        )
        ON COMMIT DELETE ROWS
    ');

    create_index_if_missing(
        'IDX_ACCT_JURNAL_DTL_STAGE_TMP',
        'CREATE INDEX IDX_ACCT_JURNAL_DTL_STAGE_TMP ON ACCT_JURNAL_DTL_STAGE_TMP (SESSION_TOKEN, BARIS)'
    );

    create_table_if_missing('ACCT_RECALC_JOB', '
        CREATE TABLE ACCT_RECALC_JOB
        (
            JOB_ID         NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
            IDDATA         VARCHAR2(20)                 NOT NULL,
            PERIODE        VARCHAR2(7)                  NOT NULL,
            JURNALID       NUMBER                       NOT NULL,
            GLMONTH        NUMBER(2)                    NOT NULL,
            GLYEAR         NUMBER(4)                    NOT NULL,
            USERID         VARCHAR2(20)                 NOT NULL,
            STATUS         VARCHAR2(16)                 NOT NULL,
            ATTEMPT_COUNT  NUMBER(3)    DEFAULT 0       NOT NULL,
            NEXT_RETRY_AT  TIMESTAMP(6) WITH TIME ZONE NULL,
            LAST_ERROR     VARCHAR2(2000)               NULL,
            CREATED_DATE   TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
            STARTED_DATE   TIMESTAMP(6) WITH TIME ZONE NULL,
            FINISHED_DATE  TIMESTAMP(6) WITH TIME ZONE NULL,
            UPDATED_DATE   TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL
        )
    ');

    create_constraint_if_missing(
        'ACCT_RECALC_JOB',
        'CK_ACCT_RECALC_JOB_STATUS',
        'ALTER TABLE ACCT_RECALC_JOB ADD CONSTRAINT CK_ACCT_RECALC_JOB_STATUS CHECK (STATUS IN (''PENDING'', ''RUNNING'', ''RETRY'', ''DONE'', ''FAILED''))'
    );

    create_index_if_missing(
        'IDX_ACCT_RECALC_JOB_DUE',
        'CREATE INDEX IDX_ACCT_RECALC_JOB_DUE ON ACCT_RECALC_JOB (STATUS, NEXT_RETRY_AT, CREATED_DATE)'
    );

    create_index_if_missing(
        'IDX_ACCT_RECALC_JOB_KEY',
        'CREATE INDEX IDX_ACCT_RECALC_JOB_KEY ON ACCT_RECALC_JOB (IDDATA, PERIODE, JURNALID, STATUS)'
    );
END;
/
