-- Purpose: Add metadata-driven accounting report engine based on ACCT_COA.
-- Date: 2026-06-27
--
-- Design notes:
--   * ACCT_COA remains the source of account hierarchy and balances.
--   * Report sections are configured in metadata tables, scoped by report code
--     and accounting type.
--   * ACCT_LAPORAN_V2.LAP_LABARUGI_V2 keeps its existing cursor contract, but
--     delegates to ACCT_REPORT_ENGINE_V1 instead of the legacy temp-table
--     generator.

DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(1)
      INTO v_count
      FROM USER_TABLES
     WHERE TABLE_NAME = 'ACCT_REPORT_DEF';

    IF v_count = 0 THEN
        EXECUTE IMMEDIATE q'[
            CREATE TABLE ACCT_REPORT_DEF (
                REPORT_CODE VARCHAR2(30) NOT NULL,
                REPORT_NAME VARCHAR2(100) NOT NULL,
                IS_ACTIVE CHAR(1) DEFAULT 'Y' NOT NULL,
                CREATED_AT DATE DEFAULT SYSDATE NOT NULL,
                CONSTRAINT PK_ACCT_REPORT_DEF PRIMARY KEY (REPORT_CODE),
                CONSTRAINT CK_ACCT_REPORT_DEF_ACTIVE CHECK (IS_ACTIVE IN ('Y', 'N'))
            )]';
    END IF;

    SELECT COUNT(1)
      INTO v_count
      FROM USER_TABLES
     WHERE TABLE_NAME = 'ACCT_REPORT_SECTION';

    IF v_count = 0 THEN
        EXECUTE IMMEDIATE q'[
            CREATE TABLE ACCT_REPORT_SECTION (
                SECTION_ID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
                REPORT_CODE VARCHAR2(30) NOT NULL,
                SECTION_CODE VARCHAR2(50) NOT NULL,
                SECTION_NAME VARCHAR2(150) NOT NULL,
                DISPLAY_ORDER NUMBER(6) NOT NULL,
                NORMAL_POSISI CHAR(1),
                SHOW_ZERO CHAR(1) DEFAULT 'N' NOT NULL,
                IS_ACTIVE CHAR(1) DEFAULT 'Y' NOT NULL,
                CREATED_AT DATE DEFAULT SYSDATE NOT NULL,
                CONSTRAINT PK_ACCT_REPORT_SECTION PRIMARY KEY (SECTION_ID),
                CONSTRAINT UK_ACCT_REPORT_SECTION UNIQUE (REPORT_CODE, SECTION_CODE),
                CONSTRAINT FK_ACCT_REPORT_SECTION_DEF FOREIGN KEY (REPORT_CODE) REFERENCES ACCT_REPORT_DEF (REPORT_CODE),
                CONSTRAINT CK_ACCT_REPORT_SECTION_POS CHECK (NORMAL_POSISI IS NULL OR NORMAL_POSISI IN ('D', 'K')),
                CONSTRAINT CK_ACCT_REPORT_SECTION_ZERO CHECK (SHOW_ZERO IN ('Y', 'N')),
                CONSTRAINT CK_ACCT_REPORT_SECTION_ACTIVE CHECK (IS_ACTIVE IN ('Y', 'N'))
            )]';
    END IF;

    SELECT COUNT(1)
      INTO v_count
      FROM USER_TABLES
     WHERE TABLE_NAME = 'ACCT_REPORT_SECTION_ACCOUNT';

    IF v_count = 0 THEN
        EXECUTE IMMEDIATE q'[
            CREATE TABLE ACCT_REPORT_SECTION_ACCOUNT (
                SECTION_ACCOUNT_ID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
                SECTION_ID NUMBER NOT NULL,
                JENIS_AKUNTING VARCHAR2(20) DEFAULT '*' NOT NULL,
                IDDATA VARCHAR2(20),
                TAHUN NUMBER(4),
                KODEACC_ROOT VARCHAR2(30) NOT NULL,
                DISPLAY_ORDER NUMBER(6) NOT NULL,
                INCLUDE_CHILDREN CHAR(1) DEFAULT 'Y' NOT NULL,
                IS_ACTIVE CHAR(1) DEFAULT 'Y' NOT NULL,
                CREATED_AT DATE DEFAULT SYSDATE NOT NULL,
                CONSTRAINT PK_ACCT_REPORT_SECTION_ACCOUNT PRIMARY KEY (SECTION_ACCOUNT_ID),
                CONSTRAINT FK_ACCT_REPORT_SEC_ACC_SECTION FOREIGN KEY (SECTION_ID) REFERENCES ACCT_REPORT_SECTION (SECTION_ID),
                CONSTRAINT CK_ACCT_REPORT_SEC_ACC_CHILD CHECK (INCLUDE_CHILDREN IN ('Y', 'N')),
                CONSTRAINT CK_ACCT_REPORT_SEC_ACC_ACTIVE CHECK (IS_ACTIVE IN ('Y', 'N'))
            )]';
    END IF;

    EXECUTE IMMEDIATE q'[
MERGE INTO ACCT_REPORT_DEF target
    USING (
        SELECT 'LABARUGI' REPORT_CODE, 'Laporan Laba Rugi' REPORT_NAME FROM DUAL
    ) source
       ON (target.REPORT_CODE = source.REPORT_CODE)
     WHEN NOT MATCHED THEN
        INSERT (REPORT_CODE, REPORT_NAME)
        VALUES (source.REPORT_CODE, source.REPORT_NAME)]';

    EXECUTE IMMEDIATE q'[
MERGE INTO ACCT_REPORT_SECTION target
    USING (
        SELECT 'LABARUGI' REPORT_CODE, 'PENDAPATAN' SECTION_CODE, 'PENDAPATAN' SECTION_NAME, 10 DISPLAY_ORDER, 'K' NORMAL_POSISI FROM DUAL UNION ALL
        SELECT 'LABARUGI', 'HPP', 'HPP', 20, 'D' FROM DUAL UNION ALL
        SELECT 'LABARUGI', 'BIAYA_UMUM_ADMIN', 'BIAYA UMUM DAN ADMINISTRASI', 30, 'D' FROM DUAL UNION ALL
        SELECT 'LABARUGI', 'PENDAPATAN_DILUAR_USAHA', 'PENDAPATAN DILUAR USAHA', 40, 'K' FROM DUAL UNION ALL
        SELECT 'LABARUGI', 'PENGELUARAN_DILUAR_USAHA', 'PENGELUARAN DILUAR USAHA', 50, 'D' FROM DUAL UNION ALL
        SELECT 'LABARUGI', 'BIAYA_TM', 'BIAYA TM', 60, 'D' FROM DUAL
    ) source
       ON (target.REPORT_CODE = source.REPORT_CODE AND target.SECTION_CODE = source.SECTION_CODE)
     WHEN MATCHED THEN
        UPDATE SET target.SECTION_NAME = source.SECTION_NAME,
                   target.DISPLAY_ORDER = source.DISPLAY_ORDER,
                   target.NORMAL_POSISI = source.NORMAL_POSISI,
                   target.IS_ACTIVE = 'Y'
     WHEN NOT MATCHED THEN
        INSERT (REPORT_CODE, SECTION_CODE, SECTION_NAME, DISPLAY_ORDER, NORMAL_POSISI)
        VALUES (source.REPORT_CODE, source.SECTION_CODE, source.SECTION_NAME, source.DISPLAY_ORDER, source.NORMAL_POSISI)]';

    EXECUTE IMMEDIATE q'[
MERGE INTO ACCT_REPORT_SECTION_ACCOUNT target
    USING (
        SELECT section.SECTION_ID, '*' JENIS_AKUNTING, CAST(NULL AS VARCHAR2(20)) IDDATA, CAST(NULL AS NUMBER) TAHUN, '4' KODEACC_ROOT, 10 DISPLAY_ORDER
          FROM ACCT_REPORT_SECTION section
         WHERE section.REPORT_CODE = 'LABARUGI'
           AND section.SECTION_CODE = 'PENDAPATAN'
        UNION ALL
        SELECT section.SECTION_ID, '*', NULL, NULL, '5', 10
          FROM ACCT_REPORT_SECTION section
         WHERE section.REPORT_CODE = 'LABARUGI'
           AND section.SECTION_CODE = 'HPP'
        UNION ALL
        SELECT section.SECTION_ID, '*', NULL, NULL, '6', 10
          FROM ACCT_REPORT_SECTION section
         WHERE section.REPORT_CODE = 'LABARUGI'
           AND section.SECTION_CODE = 'BIAYA_UMUM_ADMIN'
        UNION ALL
        SELECT section.SECTION_ID, '*', NULL, NULL, '7', 10
          FROM ACCT_REPORT_SECTION section
         WHERE section.REPORT_CODE = 'LABARUGI'
           AND section.SECTION_CODE = 'PENDAPATAN_DILUAR_USAHA'
        UNION ALL
        SELECT section.SECTION_ID, '*', NULL, NULL, '8', 10
          FROM ACCT_REPORT_SECTION section
         WHERE section.REPORT_CODE = 'LABARUGI'
           AND section.SECTION_CODE = 'PENGELUARAN_DILUAR_USAHA'
        UNION ALL
        SELECT section.SECTION_ID, '*', NULL, NULL, '80', 10
          FROM ACCT_REPORT_SECTION section
         WHERE section.REPORT_CODE = 'LABARUGI'
           AND section.SECTION_CODE = 'BIAYA_TM'
        UNION ALL
        SELECT section.SECTION_ID, '*', NULL, NULL, '81', 20
          FROM ACCT_REPORT_SECTION section
         WHERE section.REPORT_CODE = 'LABARUGI'
           AND section.SECTION_CODE = 'BIAYA_TM'
    ) source
       ON (target.SECTION_ID = source.SECTION_ID
       AND target.JENIS_AKUNTING = source.JENIS_AKUNTING
       AND NVL(target.IDDATA, '*') = NVL(source.IDDATA, '*')
       AND NVL(target.TAHUN, 0) = NVL(source.TAHUN, 0)
       AND target.KODEACC_ROOT = source.KODEACC_ROOT)
     WHEN MATCHED THEN
        UPDATE SET target.DISPLAY_ORDER = source.DISPLAY_ORDER,
                   target.IS_ACTIVE = 'Y'
     WHEN NOT MATCHED THEN
        INSERT (SECTION_ID, JENIS_AKUNTING, IDDATA, TAHUN, KODEACC_ROOT, DISPLAY_ORDER)
        VALUES (source.SECTION_ID, source.JENIS_AKUNTING, source.IDDATA, source.TAHUN, source.KODEACC_ROOT, source.DISPLAY_ORDER)]';
    EXECUTE IMMEDIATE q'[
CREATE OR REPLACE PACKAGE ACCT_REPORT_ENGINE_V1 AS
    PROCEDURE GET_REPORT(
        p_IDDATA          IN  VARCHAR2,
        p_BULAN           IN  INTEGER,
        p_TAHUN           IN  INTEGER,
        p_USERID          IN  VARCHAR2,
        p_REPORT_CODE     IN  VARCHAR2,
        p_JENISAKUNTING   IN  VARCHAR2,
        p_CURSOR          OUT SYS_REFCURSOR
    );

    PROCEDURE GET_DRILLDOWN(
        p_IDDATA          IN  VARCHAR2,
        p_BULAN           IN  INTEGER,
        p_TAHUN           IN  INTEGER,
        p_REPORT_CODE     IN  VARCHAR2,
        p_SECTION_ID      IN  NUMBER,
        p_KODEACC         IN  VARCHAR2,
        p_CURSOR          OUT SYS_REFCURSOR
    );
END ACCT_REPORT_ENGINE_V1;]';

    EXECUTE IMMEDIATE q'[
CREATE OR REPLACE PACKAGE BODY ACCT_REPORT_ENGINE_V1 AS
    FUNCTION NetAmount(
        p_debet IN NUMBER,
        p_kredit IN NUMBER,
        p_posisi IN VARCHAR2
    ) RETURN NUMBER
    IS
    BEGIN
        IF p_posisi = 'K' THEN
            RETURN NVL(p_kredit, 0) - NVL(p_debet, 0);
        END IF;

        RETURN NVL(p_debet, 0) - NVL(p_kredit, 0);
    END NetAmount;

    PROCEDURE ValidateMonth(p_bulan IN INTEGER)
    IS
    BEGIN
        IF p_bulan < 1 OR p_bulan > 12 THEN
            RAISE_APPLICATION_ERROR(-20090, 'Bulan laporan tidak valid: ' || p_bulan);
        END IF;
    END ValidateMonth;

    PROCEDURE GET_REPORT(
        p_IDDATA          IN  VARCHAR2,
        p_BULAN           IN  INTEGER,
        p_TAHUN           IN  INTEGER,
        p_USERID          IN  VARCHAR2,
        p_REPORT_CODE     IN  VARCHAR2,
        p_JENISAKUNTING   IN  VARCHAR2,
        p_CURSOR          OUT SYS_REFCURSOR
    )
    IS
    BEGIN
        ValidateMonth(p_BULAN);

        OPEN p_CURSOR FOR
            WITH section_accounts AS (
                SELECT section.SECTION_ID,
                       section.SECTION_CODE,
                       section.SECTION_NAME,
                       section.DISPLAY_ORDER SECTION_ORDER,
                       NVL(section.NORMAL_POSISI, 'D') NORMAL_POSISI,
                       section.SHOW_ZERO,
                       account.KODEACC_ROOT,
                       account.DISPLAY_ORDER ACCOUNT_ORDER
                  FROM ACCT_REPORT_SECTION section
                  JOIN ACCT_REPORT_SECTION_ACCOUNT account
                    ON account.SECTION_ID = section.SECTION_ID
                 WHERE section.REPORT_CODE = p_REPORT_CODE
                   AND section.IS_ACTIVE = 'Y'
                   AND account.IS_ACTIVE = 'Y'
                   AND account.JENIS_AKUNTING IN ('*', p_JENISAKUNTING)
                   AND (account.IDDATA IS NULL OR account.IDDATA = p_IDDATA)
                   AND (account.TAHUN IS NULL OR account.TAHUN = p_TAHUN)
            ),
            coa_tree AS (
                SELECT section_accounts.SECTION_ID,
                       section_accounts.SECTION_CODE,
                       section_accounts.SECTION_NAME,
                       section_accounts.SECTION_ORDER,
                       section_accounts.NORMAL_POSISI,
                       section_accounts.SHOW_ZERO,
                       section_accounts.KODEACC_ROOT,
                       section_accounts.ACCOUNT_ORDER,
                       coa.IDDATA,
                       coa.KODEACC,
                       coa.PARENTACC,
                       coa.NAMAACC,
                       coa.LVL,
                       coa.POSISI,
                       coa.ISHEADER,
                       coa."1D", coa."1K", coa."2D", coa."2K", coa."3D", coa."3K",
                       coa."4D", coa."4K", coa."5D", coa."5K", coa."6D", coa."6K",
                       coa."7D", coa."7K", coa."8D", coa."8K", coa."9D", coa."9K",
                       coa."10D", coa."10K", coa."11D", coa."11K", coa."12D", coa."12K"
                  FROM section_accounts
                  JOIN ACCT_COA coa
                    ON coa.IDDATA = p_IDDATA
                   AND coa.TAHUN = p_TAHUN
                 START WITH coa.KODEACC = section_accounts.KODEACC_ROOT
                CONNECT BY NOCYCLE PRIOR coa.KODEACC = coa.PARENTACC
                       AND PRIOR section_accounts.SECTION_ID = section_accounts.SECTION_ID
                       AND PRIOR section_accounts.KODEACC_ROOT = section_accounts.KODEACC_ROOT
            ),
            calculated AS (
                SELECT coa_tree.IDDATA,
                       coa_tree.KODEACC,
                       coa_tree.SECTION_ORDER * 1000 + coa_tree.ACCOUNT_ORDER + ROW_NUMBER() OVER (PARTITION BY coa_tree.SECTION_ID ORDER BY coa_tree.KODEACC) URUT,
                       coa_tree.SECTION_NAME TIPEACC,
                       coa_tree.SECTION_NAME SUB1,
                       coa_tree.NAMAACC SUB2,
                       CAST(NULL AS VARCHAR2(150)) SUB3,
                       CAST(NULL AS VARCHAR2(150)) SUB4,
                       CAST(NULL AS VARCHAR2(150)) SUB5,
                       CAST(NULL AS VARCHAR2(150)) SUB6,
                       CASE p_BULAN
                           WHEN 1 THEN NetAmount(coa_tree."1D", coa_tree."1K", coa_tree.NORMAL_POSISI)
                           WHEN 2 THEN NetAmount(coa_tree."2D", coa_tree."2K", coa_tree.NORMAL_POSISI)
                           WHEN 3 THEN NetAmount(coa_tree."3D", coa_tree."3K", coa_tree.NORMAL_POSISI)
                           WHEN 4 THEN NetAmount(coa_tree."4D", coa_tree."4K", coa_tree.NORMAL_POSISI)
                           WHEN 5 THEN NetAmount(coa_tree."5D", coa_tree."5K", coa_tree.NORMAL_POSISI)
                           WHEN 6 THEN NetAmount(coa_tree."6D", coa_tree."6K", coa_tree.NORMAL_POSISI)
                           WHEN 7 THEN NetAmount(coa_tree."7D", coa_tree."7K", coa_tree.NORMAL_POSISI)
                           WHEN 8 THEN NetAmount(coa_tree."8D", coa_tree."8K", coa_tree.NORMAL_POSISI)
                           WHEN 9 THEN NetAmount(coa_tree."9D", coa_tree."9K", coa_tree.NORMAL_POSISI)
                           WHEN 10 THEN NetAmount(coa_tree."10D", coa_tree."10K", coa_tree.NORMAL_POSISI)
                           WHEN 11 THEN NetAmount(coa_tree."11D", coa_tree."11K", coa_tree.NORMAL_POSISI)
                           WHEN 12 THEN NetAmount(coa_tree."12D", coa_tree."12K", coa_tree.NORMAL_POSISI)
                       END BULANINI,
                       NetAmount(
                           NVL(coa_tree."1D", 0)
                           + CASE WHEN p_BULAN >= 2 THEN NVL(coa_tree."2D", 0) ELSE 0 END
                           + CASE WHEN p_BULAN >= 3 THEN NVL(coa_tree."3D", 0) ELSE 0 END
                           + CASE WHEN p_BULAN >= 4 THEN NVL(coa_tree."4D", 0) ELSE 0 END
                           + CASE WHEN p_BULAN >= 5 THEN NVL(coa_tree."5D", 0) ELSE 0 END
                           + CASE WHEN p_BULAN >= 6 THEN NVL(coa_tree."6D", 0) ELSE 0 END
                           + CASE WHEN p_BULAN >= 7 THEN NVL(coa_tree."7D", 0) ELSE 0 END
                           + CASE WHEN p_BULAN >= 8 THEN NVL(coa_tree."8D", 0) ELSE 0 END
                           + CASE WHEN p_BULAN >= 9 THEN NVL(coa_tree."9D", 0) ELSE 0 END
                           + CASE WHEN p_BULAN >= 10 THEN NVL(coa_tree."10D", 0) ELSE 0 END
                           + CASE WHEN p_BULAN >= 11 THEN NVL(coa_tree."11D", 0) ELSE 0 END
                           + CASE WHEN p_BULAN >= 12 THEN NVL(coa_tree."12D", 0) ELSE 0 END,
                           NVL(coa_tree."1K", 0)
                           + CASE WHEN p_BULAN >= 2 THEN NVL(coa_tree."2K", 0) ELSE 0 END
                           + CASE WHEN p_BULAN >= 3 THEN NVL(coa_tree."3K", 0) ELSE 0 END
                           + CASE WHEN p_BULAN >= 4 THEN NVL(coa_tree."4K", 0) ELSE 0 END
                           + CASE WHEN p_BULAN >= 5 THEN NVL(coa_tree."5K", 0) ELSE 0 END
                           + CASE WHEN p_BULAN >= 6 THEN NVL(coa_tree."6K", 0) ELSE 0 END
                           + CASE WHEN p_BULAN >= 7 THEN NVL(coa_tree."7K", 0) ELSE 0 END
                           + CASE WHEN p_BULAN >= 8 THEN NVL(coa_tree."8K", 0) ELSE 0 END
                           + CASE WHEN p_BULAN >= 9 THEN NVL(coa_tree."9K", 0) ELSE 0 END
                           + CASE WHEN p_BULAN >= 10 THEN NVL(coa_tree."10K", 0) ELSE 0 END
                           + CASE WHEN p_BULAN >= 11 THEN NVL(coa_tree."11K", 0) ELSE 0 END
                           + CASE WHEN p_BULAN >= 12 THEN NVL(coa_tree."12K", 0) ELSE 0 END,
                           coa_tree.NORMAL_POSISI
                       ) TAHUNINI,
                       p_REPORT_CODE JENIS,
                       coa_tree.SECTION_CODE SETSUB,
                       p_USERID USERGEN,
                       coa_tree.ISHEADER,
                       coa_tree.SHOW_ZERO
                  FROM coa_tree
            )
            SELECT IDDATA, KODEACC, URUT, TIPEACC,
                   SUB1, SUB2, SUB3, SUB4, SUB5, SUB6,
                   BULANINI, TAHUNINI, JENIS, SETSUB, USERGEN, ISHEADER
              FROM calculated
             WHERE SHOW_ZERO = 'Y'
                OR BULANINI <> 0
                OR TAHUNINI <> 0
             ORDER BY URUT, KODEACC;
    END GET_REPORT;

    PROCEDURE GET_DRILLDOWN(
        p_IDDATA          IN  VARCHAR2,
        p_BULAN           IN  INTEGER,
        p_TAHUN           IN  INTEGER,
        p_REPORT_CODE     IN  VARCHAR2,
        p_SECTION_ID      IN  NUMBER,
        p_KODEACC         IN  VARCHAR2,
        p_CURSOR          OUT SYS_REFCURSOR
    )
    IS
    BEGIN
        ValidateMonth(p_BULAN);

        OPEN p_CURSOR FOR
            SELECT coa.KODEACC,
                   coa.NAMAACC,
                   coa.PARENTACC,
                   coa.POSISI,
                   coa.ISHEADER,
                   coa.LVL,
                   CASE p_BULAN
                       WHEN 1 THEN NetAmount(coa."1D", coa."1K", NVL(coa.POSISI, 'D'))
                       WHEN 2 THEN NetAmount(coa."2D", coa."2K", NVL(coa.POSISI, 'D'))
                       WHEN 3 THEN NetAmount(coa."3D", coa."3K", NVL(coa.POSISI, 'D'))
                       WHEN 4 THEN NetAmount(coa."4D", coa."4K", NVL(coa.POSISI, 'D'))
                       WHEN 5 THEN NetAmount(coa."5D", coa."5K", NVL(coa.POSISI, 'D'))
                       WHEN 6 THEN NetAmount(coa."6D", coa."6K", NVL(coa.POSISI, 'D'))
                       WHEN 7 THEN NetAmount(coa."7D", coa."7K", NVL(coa.POSISI, 'D'))
                       WHEN 8 THEN NetAmount(coa."8D", coa."8K", NVL(coa.POSISI, 'D'))
                       WHEN 9 THEN NetAmount(coa."9D", coa."9K", NVL(coa.POSISI, 'D'))
                       WHEN 10 THEN NetAmount(coa."10D", coa."10K", NVL(coa.POSISI, 'D'))
                       WHEN 11 THEN NetAmount(coa."11D", coa."11K", NVL(coa.POSISI, 'D'))
                       WHEN 12 THEN NetAmount(coa."12D", coa."12K", NVL(coa.POSISI, 'D'))
                   END BULANINI
              FROM ACCT_COA coa
             WHERE coa.IDDATA = p_IDDATA
               AND coa.TAHUN = p_TAHUN
             START WITH coa.KODEACC = p_KODEACC
            CONNECT BY NOCYCLE PRIOR coa.KODEACC = coa.PARENTACC
             ORDER BY coa.KODEACC;
    END GET_DRILLDOWN;
END ACCT_REPORT_ENGINE_V1;]';

    EXECUTE IMMEDIATE q'[
CREATE OR REPLACE PACKAGE ACCT_LAPORAN_V2 AS
    PROCEDURE LAP_LABARUGI_V2(
        p_IDDATA        IN  VARCHAR2,
        p_BULAN         IN  INTEGER,
        p_TAHUN         IN  INTEGER,
        p_USERID        IN  VARCHAR2,
        p_JENISAKUNTING IN  VARCHAR2,
        p_CURSOR        OUT SYS_REFCURSOR
    );

    PROCEDURE LAP_LABARUGI_SUB_V2(
        p_IDDATA  IN  VARCHAR2,
        p_BULAN   IN  INTEGER,
        p_TAHUN   IN  INTEGER,
        p_KODEACC IN  VARCHAR2,
        p_USERID  IN  VARCHAR2,
        p_LAP     IN  VARCHAR2,
        p_POSISI  IN  VARCHAR2,
        p_CURSOR  OUT SYS_REFCURSOR
    );
END ACCT_LAPORAN_V2;]';

    EXECUTE IMMEDIATE q'[
CREATE OR REPLACE PACKAGE BODY ACCT_LAPORAN_V2 AS
    PROCEDURE LAP_LABARUGI_V2(
        p_IDDATA        IN  VARCHAR2,
        p_BULAN         IN  INTEGER,
        p_TAHUN         IN  INTEGER,
        p_USERID        IN  VARCHAR2,
        p_JENISAKUNTING IN  VARCHAR2,
        p_CURSOR        OUT SYS_REFCURSOR
    )
    IS
    BEGIN
        ACCT_REPORT_ENGINE_V1.GET_REPORT(
            p_IDDATA,
            p_BULAN,
            p_TAHUN,
            p_USERID,
            'LABARUGI',
            p_JENISAKUNTING,
            p_CURSOR
        );
    END LAP_LABARUGI_V2;

    PROCEDURE LAP_LABARUGI_SUB_V2(
        p_IDDATA  IN  VARCHAR2,
        p_BULAN   IN  INTEGER,
        p_TAHUN   IN  INTEGER,
        p_KODEACC IN  VARCHAR2,
        p_USERID  IN  VARCHAR2,
        p_LAP     IN  VARCHAR2,
        p_POSISI  IN  VARCHAR2,
        p_CURSOR  OUT SYS_REFCURSOR
    )
    IS
        v_ignore NUMBER;
    BEGIN
        v_ignore := ACCT_LAPORAN.ACC_GENREP_LRNR_SUB(
            p_IDDATA,
            p_BULAN,
            p_TAHUN,
            p_KODEACC,
            p_USERID,
            p_LAP,
            p_POSISI
        );

        OPEN p_CURSOR FOR
            SELECT *
              FROM ACC_SUB_REPORT
             WHERE IDDATA = p_IDDATA
               AND GENUSER = p_USERID;
    END LAP_LABARUGI_SUB_V2;
END ACCT_LAPORAN_V2;]';

    DBMS_OUTPUT.PUT_LINE('CREATED ACCT_REPORT_ENGINE_V1 AND LABARUGI METADATA');
END;
/



