-- Purpose: Validate Oracle execution plan before/after jurnal index tuning.
-- Date: 2026-03-18

-- Replace sample values as needed.
DEFINE P_IDDATA = 'SAMPLE_IDDATA';
DEFINE P_PERIODE = '03/2026';
DEFINE P_GLYEAR = 2026;
DEFINE P_DARIBULAN = 1;
DEFINE P_SAMPAIBULAN = 3;
DEFINE P_DARI_YEAR = 2025;
DEFINE P_DARI_MONTH = 12;
DEFINE P_SAMPAI_YEAR = 2026;
DEFINE P_SAMPAI_MONTH = 3;

ALTER SESSION SET NLS_DATE_FORMAT = 'YYYY-MM-DD';

EXPLAIN PLAN SET STATEMENT_ID = 'Q1_HDR_PERIOD' FOR
SELECT JURNALID, HID, NOJURNAL, TANGGAL
  FROM ACCT_JURNAL_HDR
 WHERE IDDATA = '&P_IDDATA'
   AND PERIODE = '&P_PERIODE'
 ORDER BY NOJURNAL;

SELECT *
  FROM TABLE(DBMS_XPLAN.DISPLAY('PLAN_TABLE', 'Q1_HDR_PERIOD', 'BASIC +PREDICATE +COST +ROWS'));

EXPLAIN PLAN SET STATEMENT_ID = 'Q2_DTL_PERIOD' FOR
SELECT REFFID, HIDREFF, NOJURNAL, TANGGAL, BARIS, KODE, REKENING, DEBET, KREDIT, KETERANGAN, POSTED, PERIODE
  FROM ACCT_JURNAL_DTL
 WHERE IDDATA = '&P_IDDATA'
   AND PERIODE = '&P_PERIODE'
 ORDER BY NOJURNAL, BARIS;

SELECT *
  FROM TABLE(DBMS_XPLAN.DISPLAY('PLAN_TABLE', 'Q2_DTL_PERIOD', 'BASIC +PREDICATE +COST +ROWS'));

EXPLAIN PLAN SET STATEMENT_ID = 'Q3_DTL_YM' FOR
SELECT REFFID, HIDREFF, NOJURNAL, TANGGAL, BARIS, KODE, REKENING, DEBET, KREDIT, KETERANGAN, POSTED, PERIODE
  FROM ACCT_JURNAL_DTL
 WHERE IDDATA = '&P_IDDATA'
   AND GLYEAR = &P_GLYEAR
   AND GLMONTH BETWEEN &P_DARIBULAN AND &P_SAMPAIBULAN;

SELECT *
  FROM TABLE(DBMS_XPLAN.DISPLAY('PLAN_TABLE', 'Q3_DTL_YM', 'BASIC +PREDICATE +COST +ROWS'));

EXPLAIN PLAN SET STATEMENT_ID = 'Q4_DTL_SEARCH' FOR
SELECT REFFID, HIDREFF, NOJURNAL, TANGGAL, BARIS, KODE, REKENING, DEBET, KREDIT, KETERANGAN, POSTED, PERIODE
  FROM ACCT_JURNAL_DTL
 WHERE IDDATA = '&P_IDDATA'
   AND (
         (GLYEAR > &P_DARI_YEAR OR (GLYEAR = &P_DARI_YEAR AND GLMONTH >= &P_DARI_MONTH))
     AND (GLYEAR < &P_SAMPAI_YEAR OR (GLYEAR = &P_SAMPAI_YEAR AND GLMONTH <= &P_SAMPAI_MONTH))
       )
 ORDER BY PERIODE, NOJURNAL, BARIS;

SELECT *
  FROM TABLE(DBMS_XPLAN.DISPLAY('PLAN_TABLE', 'Q4_DTL_SEARCH', 'BASIC +PREDICATE +COST +ROWS'));
