SET LINESIZE 32767
SET PAGESIZE 0
SET FEEDBACK OFF
SET VERIFY OFF
SET HEADING OFF
SELECT text FROM user_source WHERE name = 'ACCT_RECALLCULATIONS' AND type = 'PACKAGE BODY' AND line BETWEEN 25 AND 50 ORDER BY line;
EXIT;
