-- Purpose:
--   Add telemetry columns for delta rekalkulasi queue on ACCT_RECALC_JOB.
-- Note:
--   Official deployment should use GLMigrator migration 20260319_004.

SET SERVEROUTPUT ON;

DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(1) INTO v_count
      FROM USER_TAB_COLUMNS
     WHERE TABLE_NAME = 'ACCT_RECALC_JOB'
       AND COLUMN_NAME = 'RECALC_SCOPE';
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE ACCT_RECALC_JOB ADD (RECALC_SCOPE VARCHAR2(20) DEFAULT ''NONE'' NOT NULL)';
        DBMS_OUTPUT.PUT_LINE('ADDED ACCT_RECALC_JOB.RECALC_SCOPE');
    END IF;

    SELECT COUNT(1) INTO v_count
      FROM USER_TAB_COLUMNS
     WHERE TABLE_NAME = 'ACCT_RECALC_JOB'
       AND COLUMN_NAME = 'IMPACTED_ACCOUNT_COUNT';
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE ACCT_RECALC_JOB ADD (IMPACTED_ACCOUNT_COUNT NUMBER(10) DEFAULT 0 NOT NULL)';
        DBMS_OUTPUT.PUT_LINE('ADDED ACCT_RECALC_JOB.IMPACTED_ACCOUNT_COUNT');
    END IF;

    SELECT COUNT(1) INTO v_count
      FROM USER_TAB_COLUMNS
     WHERE TABLE_NAME = 'ACCT_RECALC_JOB'
       AND COLUMN_NAME = 'IMPACTED_ROW_COUNT';
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE ACCT_RECALC_JOB ADD (IMPACTED_ROW_COUNT NUMBER(10) DEFAULT 0 NOT NULL)';
        DBMS_OUTPUT.PUT_LINE('ADDED ACCT_RECALC_JOB.IMPACTED_ROW_COUNT');
    END IF;

    SELECT COUNT(1) INTO v_count
      FROM USER_INDEXES
     WHERE INDEX_NAME = 'IDX_ACCT_RECALC_JOB_SCOPE';
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'CREATE INDEX IDX_ACCT_RECALC_JOB_SCOPE ON ACCT_RECALC_JOB (STATUS, RECALC_SCOPE, CREATED_DATE)';
        DBMS_OUTPUT.PUT_LINE('CREATED IDX_ACCT_RECALC_JOB_SCOPE');
    END IF;
END;
/
