-- Sample master and transaction seed for Fixed Asset module
-- Replace :p_iddata and account codes based on your environment before execution.

DEFINE p_iddata = 'ID01';

-- Category
INSERT INTO ACCT_FA_CATEGORY (IDDATA, CATEGORY_CODE, CATEGORY_NAME, CREATED_BY)
SELECT '&p_iddata', 'MCH', 'Machinery', 'SYSTEM' FROM DUAL
WHERE NOT EXISTS (
    SELECT 1 FROM ACCT_FA_CATEGORY WHERE IDDATA='&p_iddata' AND CATEGORY_CODE='MCH'
);

-- Group
INSERT INTO ACCT_FA_GROUP (IDDATA, CATEGORY_ID, GROUP_CODE, GROUP_NAME, CREATED_BY)
SELECT '&p_iddata', C.CATEGORY_ID, 'MCH-PROD', 'Production Machinery', 'SYSTEM'
FROM ACCT_FA_CATEGORY C
WHERE C.IDDATA='&p_iddata' AND C.CATEGORY_CODE='MCH'
  AND NOT EXISTS (
      SELECT 1 FROM ACCT_FA_GROUP G WHERE G.IDDATA='&p_iddata' AND G.GROUP_CODE='MCH-PROD'
  );

-- Account mapping
INSERT INTO ACCT_FA_ACCOUNT_MAP
(IDDATA, CATEGORY_ID, ASSET_ACCT, ACC_DEPR_ACCT, DEPR_EXP_ACCT, GAIN_DISP_ACCT, LOSS_DISP_ACCT, CIP_ACCT, IS_ACTIVE, CREATED_BY)
SELECT '&p_iddata', C.CATEGORY_ID, '15.10001.001', '15.20001.001', '61.30001.001', '81.10001.001', '82.10001.001', '15.90001.001', 'Y', 'SYSTEM'
FROM ACCT_FA_CATEGORY C
WHERE C.IDDATA='&p_iddata' AND C.CATEGORY_CODE='MCH'
  AND NOT EXISTS (
      SELECT 1 FROM ACCT_FA_ACCOUNT_MAP M WHERE M.IDDATA='&p_iddata' AND M.CATEGORY_ID=C.CATEGORY_ID AND M.IS_ACTIVE='Y'
  );

-- Asset sample
INSERT INTO ACCT_FA_ASSET
(
    IDDATA, ASSET_CODE, ASSET_NAME, CATEGORY_ID, GROUP_ID, ACQUISITION_DATE, IN_SERVICE_DATE, DEPRECIATION_START_DATE,
    ACQUISITION_COST, RESIDUAL_VALUE, USEFUL_LIFE_MONTHS, DEPR_METHOD, STATUS,
    DEPARTMENT_ID, COST_CENTER_ID, LOCATION_ID, CURRENCY_CODE, EXCHANGE_RATE, CREATED_BY
)
SELECT
    '&p_iddata',
    'ID01-MCH-2026-000123',
    'Mesin Produksi A',
    C.CATEGORY_ID,
    G.GROUP_ID,
    DATE '2026-01-10',
    DATE '2026-01-20',
    DATE '2026-01-20',
    1200000000,
    120000000,
    120,
    'SL',
    'ACTIVE',
    'DPT-PRD',
    'CC-PRD-01',
    'LOC-PLANT-1',
    'IDR',
    1,
    'SYSTEM'
FROM ACCT_FA_CATEGORY C
JOIN ACCT_FA_GROUP G
  ON G.CATEGORY_ID = C.CATEGORY_ID
 AND G.IDDATA = C.IDDATA
WHERE C.IDDATA='&p_iddata' AND C.CATEGORY_CODE='MCH' AND G.GROUP_CODE='MCH-PROD'
  AND NOT EXISTS (
      SELECT 1 FROM ACCT_FA_ASSET A WHERE A.IDDATA='&p_iddata' AND A.ASSET_CODE='ID01-MCH-2026-000123'
  );

-- Improvement transaction sample (draft)
INSERT INTO ACCT_FA_TRX_HDR
(
    IDDATA, DOC_NO, TRX_TYPE, DOC_DATE, PERIOD, PERIOD_KEY, ASSET_ID,
    AMOUNT_BASE, CURRENCY_CODE, EXCHANGE_RATE, STATUS, SOURCE_REF_NO, REMARKS, CREATED_BY
)
SELECT
    '&p_iddata',
    'FA-IMP/&p_iddata/202607/000001',
    'IMPROVEMENT',
    DATE '2026-07-15',
    '07/2026',
    202607,
    A.ASSET_ID,
    150000000,
    'IDR',
    1,
    'DRAFT',
    'PO-FA-2026-0715',
    'Additional capitalization for performance upgrade',
    'SYSTEM'
FROM ACCT_FA_ASSET A
WHERE A.IDDATA='&p_iddata' AND A.ASSET_CODE='ID01-MCH-2026-000123'
  AND NOT EXISTS (
      SELECT 1 FROM ACCT_FA_TRX_HDR T WHERE T.IDDATA='&p_iddata' AND T.DOC_NO='FA-IMP/&p_iddata/202607/000001'
  );

COMMIT;
