-- Fixed Asset smoke test (post-deploy / pre-release).
-- Output is read-only and safe to run repeatedly.

DEFINE P_IDDATA = 'MSLKEBUN'
DEFINE P_PERIOD = '12/2020'

SET VERIFY OFF
SET SERVEROUTPUT ON

PROMPT === Last 10 depreciation runs ===
SELECT *
FROM (
    SELECT
        R.RUN_ID,
        R.IDDATA,
        R.PERIOD,
        R.STATUS,
        R.TOTAL_AMOUNT,
        R.NOJURNAL,
        R.JURNALID,
        R.CREATED_DATE,
        R.POSTED_DATE
    FROM ACCT_FA_DEPR_RUN R
    WHERE R.IDDATA = '&P_IDDATA'
      AND R.PERIOD = '&P_PERIOD'
    ORDER BY R.RUN_ID DESC
)
WHERE ROWNUM <= 10;

PROMPT === Run detail consistency ===
SELECT
    R.RUN_ID,
    R.STATUS,
    COUNT(D.RUN_DTL_ID) AS DTL_COUNT,
    NVL(SUM(D.DEPR_AMOUNT), 0) AS DTL_AMOUNT,
    R.TOTAL_AMOUNT
FROM ACCT_FA_DEPR_RUN R
LEFT JOIN ACCT_FA_DEPR_RUN_DTL D
       ON D.RUN_ID = R.RUN_ID
WHERE R.IDDATA = '&P_IDDATA'
  AND R.PERIOD = '&P_PERIOD'
GROUP BY R.RUN_ID, R.STATUS, R.TOTAL_AMOUNT
ORDER BY R.RUN_ID DESC;

PROMPT === Posted run must have journal linkage ===
SELECT
    R.RUN_ID,
    R.STATUS,
    R.NOJURNAL,
    R.JURNALID
FROM ACCT_FA_DEPR_RUN R
WHERE R.IDDATA = '&P_IDDATA'
  AND R.PERIOD = '&P_PERIOD'
  AND R.STATUS = 'POSTED'
  AND (R.NOJURNAL IS NULL OR R.JURNALID IS NULL);

PROMPT === Depreciation history duplicates (must be zero rows) ===
SELECT
    H.ASSET_ID,
    H.PERIOD,
    COUNT(*) AS DUP_COUNT
FROM ACCT_FA_DEPR_HISTORY H
WHERE H.IDDATA = '&P_IDDATA'
  AND H.PERIOD = '&P_PERIOD'
GROUP BY H.ASSET_ID, H.PERIOD
HAVING COUNT(*) > 1;

PROMPT === Journal balance check for FA journals ===
SELECT
    H.NOJURNAL,
    NVL(SUM(D.DEBET), 0) AS TOTAL_DEBET,
    NVL(SUM(D.KREDIT), 0) AS TOTAL_KREDIT,
    NVL(SUM(D.DEBET), 0) - NVL(SUM(D.KREDIT), 0) AS SELISIH
FROM ACCT_JURNAL_HDR H
JOIN ACCT_JURNAL_DTL D
  ON D.IDDATA = H.IDDATA
 AND D.PERIODE = H.PERIODE
 AND D.NOJURNAL = H.NOJURNAL
WHERE H.IDDATA = '&P_IDDATA'
  AND H.PERIODE = '&P_PERIOD'
  AND H.NOJURNAL LIKE 'FA/%'
GROUP BY H.NOJURNAL
ORDER BY H.NOJURNAL;

PROMPT === Approval transactions requiring workflow ===
SELECT
    T.TRX_ID,
    T.DOC_NO,
    T.TRX_TYPE,
    T.STATUS,
    COUNT(A.APPROVAL_DTL_ID) AS APV_ROWS
FROM ACCT_FA_TRX_HDR T
LEFT JOIN ACCT_FA_APPROVAL_DTL A
       ON A.TRX_ID = T.TRX_ID
WHERE T.IDDATA = '&P_IDDATA'
  AND T.PERIOD = '&P_PERIOD'
  AND T.TRX_TYPE IN ('REVALUATION', 'WRITE_OFF', 'FULL_DISPOSAL', 'SALE')
GROUP BY T.TRX_ID, T.DOC_NO, T.TRX_TYPE, T.STATUS
ORDER BY T.TRX_ID DESC;

PROMPT === Approved lifecycle transaction impact to asset ===
SELECT
    T.TRX_ID,
    T.TRX_TYPE,
    T.STATUS AS TRX_STATUS,
    T.ASSET_ID,
    A.STATUS AS ASSET_STATUS,
    A.ACQUISITION_COST,
    A.IMPROVEMENT_TOTAL,
    A.REVALUATION_DELTA_TOTAL
FROM ACCT_FA_TRX_HDR T
JOIN ACCT_FA_ASSET A
  ON A.ASSET_ID = T.ASSET_ID
 AND A.IDDATA = T.IDDATA
WHERE T.IDDATA = '&P_IDDATA'
  AND T.PERIOD = '&P_PERIOD'
  AND T.STATUS IN ('APPROVED', 'POSTED')
ORDER BY T.TRX_ID DESC;

PROMPT === Mandatory lifecycle trx should be posted with journal ===
SELECT
    T.TRX_ID,
    T.TRX_TYPE,
    T.STATUS,
    T.NOJURNAL,
    T.JURNALID
FROM ACCT_FA_TRX_HDR T
WHERE T.IDDATA = '&P_IDDATA'
  AND T.PERIOD = '&P_PERIOD'
  AND T.TRX_TYPE IN ('REVALUATION', 'WRITE_OFF', 'FULL_DISPOSAL', 'SALE')
  AND T.STATUS = 'POSTED'
  AND (T.NOJURNAL IS NULL OR T.JURNALID IS NULL)
ORDER BY T.TRX_ID DESC;
