-- Fixed Asset cleanup script for targeted test artifacts.
-- Safe usage:
-- 1) Set variables explicitly before running.
-- 2) Keep scope narrow (single NOJURNAL / DOC_NO / RUN_ID).
-- 3) Review preview counts before COMMIT.

DEFINE P_IDDATA = 'MSLKEBUN'
DEFINE P_PERIOD = '12/2020'
DEFINE P_NOJURNAL = 'FA/202012/000001'
DEFINE P_DOC_NO = 'FA-REV/MSLKEBUN/202012/000001'
DEFINE P_RUN_ID = 1

SET SERVEROUTPUT ON
SET VERIFY OFF

PROMPT === Preview before cleanup ===
SELECT '&P_NOJURNAL' AS NOJURNAL, COUNT(*) AS CNT
FROM ACCT_JURNAL_HDR
WHERE IDDATA = '&P_IDDATA'
  AND PERIODE = '&P_PERIOD'
  AND NOJURNAL = '&P_NOJURNAL';

SELECT '&P_DOC_NO' AS DOC_NO, COUNT(*) AS CNT
FROM ACCT_FA_TRX_HDR
WHERE IDDATA = '&P_IDDATA'
  AND PERIOD = '&P_PERIOD'
  AND DOC_NO = '&P_DOC_NO';

SELECT TO_NUMBER('&P_RUN_ID') AS RUN_ID, COUNT(*) AS CNT
FROM ACCT_FA_DEPR_RUN
WHERE IDDATA = '&P_IDDATA'
  AND RUN_ID = TO_NUMBER('&P_RUN_ID');

PROMPT === Execute cleanup ===
DELETE FROM ACCT_FA_AUDIT_LOG
WHERE IDDATA = '&P_IDDATA'
  AND DOC_NO IN ('&P_DOC_NO', '&P_NOJURNAL');

DELETE FROM ACCT_FA_APPROVAL_DTL
WHERE TRX_ID IN (
    SELECT TRX_ID
    FROM ACCT_FA_TRX_HDR
    WHERE IDDATA = '&P_IDDATA'
      AND PERIOD = '&P_PERIOD'
      AND DOC_NO = '&P_DOC_NO'
);

DECLARE
    v_table_exists NUMBER := 0;
BEGIN
    SELECT COUNT(1)
    INTO v_table_exists
    FROM USER_TABLES
    WHERE TABLE_NAME = 'ACCT_FA_TRX_DTL';

    IF v_table_exists > 0 THEN
        EXECUTE IMMEDIATE '
            DELETE FROM ACCT_FA_TRX_DTL
            WHERE TRX_ID IN (
                SELECT TRX_ID
                FROM ACCT_FA_TRX_HDR
                WHERE IDDATA = :p_iddata
                  AND PERIOD = :p_period
                  AND DOC_NO = :p_doc_no
            )'
        USING '&P_IDDATA', '&P_PERIOD', '&P_DOC_NO';
    END IF;
END;
/

DELETE FROM ACCT_FA_TRX_HDR
WHERE IDDATA = '&P_IDDATA'
  AND PERIOD = '&P_PERIOD'
  AND DOC_NO = '&P_DOC_NO';

DELETE FROM ACCT_FA_DEPR_HISTORY
WHERE IDDATA = '&P_IDDATA'
  AND RUN_ID = TO_NUMBER('&P_RUN_ID');

DELETE FROM ACCT_FA_DEPR_RUN_DTL
WHERE RUN_ID = TO_NUMBER('&P_RUN_ID');

DELETE FROM ACCT_FA_DEPR_RUN
WHERE IDDATA = '&P_IDDATA'
  AND RUN_ID = TO_NUMBER('&P_RUN_ID');

DELETE FROM ACCT_JURNAL_DTL
WHERE IDDATA = '&P_IDDATA'
  AND PERIODE = '&P_PERIOD'
  AND NOJURNAL = '&P_NOJURNAL';

DELETE FROM ACCT_JURNAL_HDR
WHERE IDDATA = '&P_IDDATA'
  AND PERIODE = '&P_PERIOD'
  AND NOJURNAL = '&P_NOJURNAL';

COMMIT;

PROMPT === Verify after cleanup ===
SELECT '&P_NOJURNAL' AS NOJURNAL, COUNT(*) AS CNT
FROM ACCT_JURNAL_HDR
WHERE IDDATA = '&P_IDDATA'
  AND PERIODE = '&P_PERIOD'
  AND NOJURNAL = '&P_NOJURNAL';

SELECT '&P_DOC_NO' AS DOC_NO, COUNT(*) AS CNT
FROM ACCT_FA_TRX_HDR
WHERE IDDATA = '&P_IDDATA'
  AND PERIOD = '&P_PERIOD'
  AND DOC_NO = '&P_DOC_NO';

SELECT TO_NUMBER('&P_RUN_ID') AS RUN_ID, COUNT(*) AS CNT
FROM ACCT_FA_DEPR_RUN
WHERE IDDATA = '&P_IDDATA'
  AND RUN_ID = TO_NUMBER('&P_RUN_ID');
