-- Purpose:
--   1) Create ACCT_JURNAL_DTL_STAGE_TMP (GTT) for set-based upsert in JurnalRepository.
--   2) Create ACCT_RECALC_JOB durable queue table for background rekalkulasi with retry.
-- Note:
--   Official deployment should use GLMigrator migration 20260319_003.

SET SERVEROUTPUT ON;

DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(1) INTO v_count FROM USER_TABLES WHERE TABLE_NAME = 'ACCT_JURNAL_DTL_STAGE_TMP';
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE '
            CREATE GLOBAL TEMPORARY TABLE ACCT_JURNAL_DTL_STAGE_TMP
            (
                SESSION_TOKEN VARCHAR2(64)  NOT NULL,
                BARIS         NUMBER(10)    NOT NULL,
                KODE          VARCHAR2(64)  NULL,
                REKENING      VARCHAR2(512) NULL,
                DEBET         NUMBER(18,2)  NULL,
                KREDIT        NUMBER(18,2)  NULL,
                KETERANGAN    VARCHAR2(512) NULL
            )
            ON COMMIT DELETE ROWS';
        DBMS_OUTPUT.PUT_LINE('CREATED ACCT_JURNAL_DTL_STAGE_TMP');
    END IF;

    SELECT COUNT(1) INTO v_count FROM USER_INDEXES WHERE INDEX_NAME = 'IDX_ACCT_JURNAL_DTL_STAGE_TMP';
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'CREATE INDEX IDX_ACCT_JURNAL_DTL_STAGE_TMP ON ACCT_JURNAL_DTL_STAGE_TMP (SESSION_TOKEN, BARIS)';
        DBMS_OUTPUT.PUT_LINE('CREATED IDX_ACCT_JURNAL_DTL_STAGE_TMP');
    END IF;

    SELECT COUNT(1) INTO v_count FROM USER_TABLES WHERE TABLE_NAME = 'ACCT_RECALC_JOB';
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE '
            CREATE TABLE ACCT_RECALC_JOB
            (
                JOB_ID         NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                IDDATA         VARCHAR2(20)                 NOT NULL,
                PERIODE        VARCHAR2(7)                  NOT NULL,
                JURNALID       NUMBER                       NOT NULL,
                GLMONTH        NUMBER(2)                    NOT NULL,
                GLYEAR         NUMBER(4)                    NOT NULL,
                USERID         VARCHAR2(20)                 NOT NULL,
                STATUS         VARCHAR2(16)                 NOT NULL,
                ATTEMPT_COUNT  NUMBER(3)    DEFAULT 0       NOT NULL,
                NEXT_RETRY_AT  TIMESTAMP(6) WITH TIME ZONE NULL,
                LAST_ERROR     VARCHAR2(2000)               NULL,
                CREATED_DATE   TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
                STARTED_DATE   TIMESTAMP(6) WITH TIME ZONE NULL,
                FINISHED_DATE  TIMESTAMP(6) WITH TIME ZONE NULL,
                UPDATED_DATE   TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL
            )';
        DBMS_OUTPUT.PUT_LINE('CREATED ACCT_RECALC_JOB');
    END IF;
END;
/
