-- Sample reporting queries for Fixed Asset module
-- Bind examples:
-- :p_iddata = company scope
-- :p_period_from = 202601 (NUMBER)
-- :p_period_to   = 202612 (NUMBER)

-- 1) Fixed Asset Register
SELECT
    A.IDDATA,
    A.ASSET_CODE,
    A.ASSET_NAME,
    C.CATEGORY_NAME,
    A.STATUS,
    A.ACQUISITION_DATE,
    A.IN_SERVICE_DATE,
    A.ACQUISITION_COST,
    A.RESIDUAL_VALUE,
    A.USEFUL_LIFE_MONTHS,
    A.DEPR_METHOD,
    A.DEPARTMENT_ID,
    A.COST_CENTER_ID,
    A.LOCATION_ID
FROM ACCT_FA_ASSET A
JOIN ACCT_FA_CATEGORY C ON C.CATEGORY_ID = A.CATEGORY_ID
WHERE A.IDDATA = :p_iddata
  AND A.IS_DELETED = 'N'
ORDER BY A.ASSET_CODE;

-- 2) Depreciation Expense per Period
SELECT
    H.PERIOD,
    SUM(H.DEPR_AMOUNT) AS TOTAL_DEPR_EXPENSE
FROM ACCT_FA_DEPR_HISTORY H
WHERE H.IDDATA = :p_iddata
  AND H.PERIOD_KEY BETWEEN :p_period_from AND :p_period_to
GROUP BY H.PERIOD, H.PERIOD_KEY
ORDER BY H.PERIOD_KEY;

-- 3) Asset Movement by Transaction Type
SELECT
    T.PERIOD,
    T.TRX_TYPE,
    COUNT(*) AS TXN_COUNT,
    SUM(T.AMOUNT_BASE) AS TOTAL_AMOUNT
FROM ACCT_FA_TRX_HDR T
WHERE T.IDDATA = :p_iddata
  AND T.PERIOD_KEY BETWEEN :p_period_from AND :p_period_to
GROUP BY T.PERIOD, T.PERIOD_KEY, T.TRX_TYPE
ORDER BY T.PERIOD_KEY, T.TRX_TYPE;

-- 4) Fully Depreciated Assets
SELECT
    A.ASSET_CODE,
    A.ASSET_NAME,
    A.ACQUISITION_COST,
    A.RESIDUAL_VALUE,
    NVL(SUM(H.DEPR_AMOUNT), 0) AS TOTAL_DEPR,
    (A.ACQUISITION_COST + A.IMPROVEMENT_TOTAL + A.REVALUATION_DELTA_TOTAL - A.IMPAIRMENT_TOTAL) - NVL(SUM(H.DEPR_AMOUNT), 0) AS NBV
FROM ACCT_FA_ASSET A
LEFT JOIN ACCT_FA_DEPR_HISTORY H
  ON H.ASSET_ID = A.ASSET_ID
 AND H.IDDATA = A.IDDATA
WHERE A.IDDATA = :p_iddata
  AND A.IS_DELETED = 'N'
GROUP BY
    A.ASSET_CODE, A.ASSET_NAME, A.ACQUISITION_COST, A.RESIDUAL_VALUE,
    A.IMPROVEMENT_TOTAL, A.REVALUATION_DELTA_TOTAL, A.IMPAIRMENT_TOTAL
HAVING ((A.ACQUISITION_COST + A.IMPROVEMENT_TOTAL + A.REVALUATION_DELTA_TOTAL - A.IMPAIRMENT_TOTAL) - NVL(SUM(H.DEPR_AMOUNT), 0)) <= A.RESIDUAL_VALUE
ORDER BY A.ASSET_CODE;
