SET PAGESIZE 200
SET LINESIZE 220
SET VERIFY OFF
COLUMN ROLE_NAME FORMAT A20
SELECT mr.ROLE_NAME, COUNT(*) AS ACCOUNTING_MAPPING_COUNT
FROM MASTER_ROLE_PERMISSIONS mrp
JOIN MASTER_ROLES mr ON mr.ROLE_ID = mrp.ROLE_ID
JOIN MASTER_PERMISSIONS mp ON mp.PERMISSION_ID = mrp.PERMISSION_ID
WHERE mp.MODULE_ID = 1
GROUP BY mr.ROLE_NAME
ORDER BY mr.ROLE_NAME;
EXIT
