SET PAGESIZE 200
SET LINESIZE 220
SET VERIFY OFF
COLUMN ROLE_NAME FORMAT A20
WITH relevant_roles AS (
    SELECT mr.ROLE_ID, mr.ROLE_NAME,
           (SELECT COUNT(1) FROM MASTER_USER_ROLES mur WHERE mur.ROLE_ID = mr.ROLE_ID AND mur.MODULE_ID = 1) AS USER_COUNT,
           CASE WHEN mr.ROLE_ID = 1 THEN 1 ELSE 0 END AS IS_PROTECTED,
           CASE WHEN UPPER(mr.ROLE_NAME) IN ('VIEWER','CHECKER','APPROVER','MAKER','USER','OPERATOR','STAFF','SUPERVISOR','ADMIN','ADMINISTRATOR','SUPERADMIN') THEN 1 ELSE 0 END AS IS_SYSTEM_ROLE
    FROM MASTER_ROLES mr
    WHERE EXISTS (
        SELECT 1
        FROM MASTER_ROLE_PERMISSIONS mrp
        JOIN MASTER_PERMISSIONS mp ON mp.PERMISSION_ID = mrp.PERMISSION_ID
        WHERE mrp.ROLE_ID = mr.ROLE_ID AND mp.MODULE_ID = 1
    )
    OR EXISTS (
        SELECT 1
        FROM MASTER_USER_ROLES mur
        WHERE mur.ROLE_ID = mr.ROLE_ID AND mur.MODULE_ID = 1
    )
)
SELECT ROLE_ID, ROLE_NAME, USER_COUNT, IS_PROTECTED, IS_SYSTEM_ROLE
FROM relevant_roles
ORDER BY CASE WHEN IS_PROTECTED = 1 THEN 0 WHEN IS_SYSTEM_ROLE = 1 THEN 1 ELSE 2 END, ROLE_NAME;
EXIT
