SET PAGESIZE 200
SET LINESIZE 220
SET VERIFY OFF
COLUMN PERMISSION_NAME FORMAT A20
SELECT PERMISSION_ID, MODULE_ID, PERMISSION_NAME, MENU, DESCRIPTION, URUT1, URUT2
FROM MASTER_PERMISSIONS
WHERE PERMISSION_NAME = 'ALL';
EXIT
