SET PAGESIZE 200
SET LINESIZE 220
SET VERIFY OFF
COLUMN TABLE_NAME FORMAT A30
COLUMN COLUMN_NAME FORMAT A30
SELECT a.TABLE_NAME, a.COLUMN_NAME, a.CONSTRAINT_NAME
FROM USER_CONS_COLUMNS a
JOIN USER_CONSTRAINTS c ON c.CONSTRAINT_NAME = a.CONSTRAINT_NAME
WHERE c.CONSTRAINT_TYPE = 'R'
  AND c.R_CONSTRAINT_NAME IN (
      SELECT CONSTRAINT_NAME FROM USER_CONSTRAINTS WHERE TABLE_NAME = 'MASTER_PERMISSIONS' AND CONSTRAINT_TYPE IN ('P','U')
  )
ORDER BY a.TABLE_NAME, a.COLUMN_NAME;
EXIT
