SET PAGESIZE 200
SET LINESIZE 220
SET VERIFY OFF
COLUMN ROLE_NAME FORMAT A20
SELECT ROLE_ID, ROLE_NAME FROM MASTER_ROLES WHERE UPPER(ROLE_NAME) IN ('MANAGER','KABAG','ASISTEN','TAMU','AUDIT','ALL') ORDER BY ROLE_ID;
EXIT
