SET PAGESIZE 200
SET LINESIZE 220
SET VERIFY OFF
COLUMN MODULE_NAME FORMAT A15
COLUMN ROLE_NAME FORMAT A20
SELECT mm.MODULE_NAME, mr.ROLE_NAME, COUNT(*) AS USER_COUNT
FROM MASTER_USER_ROLES mur
JOIN MASTER_ROLES mr ON mr.ROLE_ID = mur.ROLE_ID
JOIN MASTER_MODULES mm ON mm.MODULE_ID = mur.MODULE_ID
WHERE UPPER(mr.ROLE_NAME) IN ('MANAGER','KABAG','ASISTEN','TAMU','AUDIT')
GROUP BY mm.MODULE_NAME, mr.ROLE_NAME
ORDER BY mr.ROLE_NAME, mm.MODULE_NAME;
EXIT
