SET PAGESIZE 200
SET LINESIZE 220
SET VERIFY OFF
COLUMN MODULE_NAME FORMAT A15
COLUMN PERMISSION_NAME FORMAT A20
SELECT mm.MODULE_NAME, mp.PERMISSION_NAME, COUNT(mrp.ROLE_ID) AS ROLE_MAPPING_COUNT
FROM MASTER_PERMISSIONS mp
JOIN MASTER_MODULES mm ON mm.MODULE_ID = mp.MODULE_ID
LEFT JOIN MASTER_ROLE_PERMISSIONS mrp ON mrp.PERMISSION_ID = mp.PERMISSION_ID
WHERE mp.PERMISSION_NAME = 'ALL'
GROUP BY mm.MODULE_NAME, mp.PERMISSION_NAME;
EXIT
