SET PAGESIZE 200
SET LINESIZE 220
SET VERIFY OFF
COLUMN MODULE_NAME FORMAT A15
COLUMN ROLE_NAME FORMAT A20
SELECT mm.MODULE_NAME, mr.ROLE_NAME, COUNT(*) AS MAPPING_COUNT
FROM MASTER_ROLE_PERMISSIONS mrp
JOIN MASTER_ROLES mr ON mr.ROLE_ID = mrp.ROLE_ID
JOIN MASTER_PERMISSIONS mp ON mp.PERMISSION_ID = mrp.PERMISSION_ID
JOIN MASTER_MODULES mm ON mm.MODULE_ID = mp.MODULE_ID
WHERE UPPER(mr.ROLE_NAME) IN ('MANAGER','KABAG','ASISTEN','TAMU','AUDIT')
GROUP BY mm.MODULE_NAME, mr.ROLE_NAME
ORDER BY mr.ROLE_NAME, mm.MODULE_NAME;
EXIT
