SET PAGESIZE 200
SET LINESIZE 220
SET VERIFY OFF
COLUMN MODULE_NAME FORMAT A15
COLUMN PERMISSION_NAME FORMAT A20
SELECT mm.MODULE_NAME, mp.PERMISSION_NAME
FROM MASTER_PERMISSIONS mp
JOIN MASTER_MODULES mm ON mm.MODULE_ID = mp.MODULE_ID
WHERE mp.PERMISSION_NAME = 'ALL'
UNION ALL
SELECT mm.MODULE_NAME, mr.ROLE_NAME
FROM MASTER_ROLES mr
CROSS JOIN (SELECT 'ROLES' AS MODULE_NAME FROM DUAL) mm
WHERE UPPER(mr.ROLE_NAME) IN ('MANAGER','KABAG','ASISTEN','TAMU','AUDIT')
ORDER BY 1, 2;
EXIT
