SET PAGESIZE 200
SET LINESIZE 220
SET VERIFY OFF
COLUMN ROLE_NAME FORMAT A20
COLUMN PERMISSION_NAME FORMAT A30
SELECT mr.ROLE_NAME, mp.PERMISSION_NAME, mrp.CAN_CREATE, mrp.CAN_READ, mrp.CAN_UPDATE, mrp.CAN_DELETE
FROM MASTER_ROLE_PERMISSIONS mrp
JOIN MASTER_ROLES mr ON mr.ROLE_ID = mrp.ROLE_ID
JOIN MASTER_PERMISSIONS mp ON mp.PERMISSION_ID = mrp.PERMISSION_ID
JOIN MASTER_MODULES mm ON mm.MODULE_ID = mp.MODULE_ID
WHERE mm.MODULE_NAME = 'FINANCE'
  AND UPPER(mr.ROLE_NAME) IN ('MANAGER','KABAG','ASISTEN','TAMU','AUDIT')
ORDER BY mr.ROLE_NAME, mp.PERMISSION_NAME;
EXIT
