SET PAGESIZE 200
SET LINESIZE 220
SET VERIFY OFF
SELECT mm.MODULE_NAME, mp.PERMISSION_NAME
FROM MASTER_PERMISSIONS mp
JOIN MASTER_MODULES mm ON mm.MODULE_ID = mp.MODULE_ID
WHERE UPPER(mp.PERMISSION_NAME) = 'ALL'
   OR UPPER(mp.PERMISSION_NAME) IN ('MANAGER','KABAG','ASISTEN','TAMU','AUDIT');
EXIT
