SET PAGESIZE 200
SET LINESIZE 220
SET VERIFY OFF
COLUMN ROLE_NAME FORMAT A20
SELECT mr.ROLE_ID, mr.ROLE_NAME, COUNT(*) AS USER_COUNT,
       LISTAGG(mur.USER_ID, ', ') WITHIN GROUP (ORDER BY mur.USER_ID) AS USERS
FROM MASTER_USER_ROLES mur
JOIN MASTER_ROLES mr ON mr.ROLE_ID = mur.ROLE_ID
JOIN MASTER_MODULES mm ON mm.MODULE_ID = mur.MODULE_ID
WHERE mm.MODULE_NAME = 'ACCOUNTING'
GROUP BY mr.ROLE_ID, mr.ROLE_NAME
ORDER BY mr.ROLE_NAME;
EXIT
