SET PAGESIZE 200
SET LINESIZE 220
SET VERIFY OFF
COLUMN ROLE_NAME FORMAT A20
SELECT mr.ROLE_ID, mr.ROLE_NAME,
       SUM(CASE WHEN mp.PERMISSION_ID IS NOT NULL THEN 1 ELSE 0 END) AS ACCOUNTING_PERMISSION_COUNT,
       SUM(CASE WHEN mur.MODULE_ID = 1 THEN 1 ELSE 0 END) AS ACCOUNTING_USER_COUNT
FROM MASTER_ROLES mr
LEFT JOIN MASTER_ROLE_PERMISSIONS mrp ON mrp.ROLE_ID = mr.ROLE_ID
LEFT JOIN MASTER_PERMISSIONS mp ON mp.PERMISSION_ID = mrp.PERMISSION_ID AND mp.MODULE_ID = 1
LEFT JOIN MASTER_USER_ROLES mur ON mur.ROLE_ID = mr.ROLE_ID AND mur.MODULE_ID = 1
GROUP BY mr.ROLE_ID, mr.ROLE_NAME
ORDER BY mr.ROLE_ID;
EXIT
