SET PAGESIZE 200
SET LINESIZE 220
SET VERIFY OFF
COLUMN ROLE_NAME FORMAT A20
COLUMN MODULE_NAME FORMAT A15
COLUMN PERMISSION_NAME FORMAT A24
SELECT mr.ROLE_ID, mr.ROLE_NAME, mm.MODULE_NAME, mp.PERMISSION_NAME, mrp.CAN_CREATE, mrp.CAN_READ, mrp.CAN_UPDATE, mrp.CAN_DELETE
FROM MASTER_ROLE_PERMISSIONS mrp
JOIN MASTER_ROLES mr ON mr.ROLE_ID = mrp.ROLE_ID
JOIN MASTER_PERMISSIONS mp ON mp.PERMISSION_ID = mrp.PERMISSION_ID
JOIN MASTER_MODULES mm ON mm.MODULE_ID = mp.MODULE_ID
WHERE mm.MODULE_NAME = 'ACCOUNTING'
ORDER BY mr.ROLE_NAME, mp.URUT1, mp.URUT2, mp.PERMISSION_NAME;
EXIT
