-- ============================================================================
-- Migration: Add Audit Trail Support to ACCT_JURNAL_HDR and ACCT_JURNAL_DTL
-- Date: 2026-03-19
-- Description: Adds audit columns (created/modified timestamps)
--              and creates ACCT_JURNAL_AUDIT log table for UPDATE/DELETE tracking.
-- ============================================================================

-- 1. Add audit columns to ACCT_JURNAL_HDR
ALTER TABLE ACCT_JURNAL_HDR ADD (
    CREATED_DATE   TIMESTAMP DEFAULT SYSTIMESTAMP,
    CREATED_BY     VARCHAR2(50),
    MODIFIED_DATE  TIMESTAMP,
    MODIFIED_BY    VARCHAR2(50),
    MODIFIED_PC    VARCHAR2(100),
    MODIFIED_IP    VARCHAR2(50)
);

-- Backfill existing rows: set CREATED_BY from USERID
UPDATE ACCT_JURNAL_HDR SET CREATED_BY = USERID, CREATED_DATE = SYSTIMESTAMP WHERE CREATED_BY IS NULL;
COMMIT;

-- 2. Add audit columns to ACCT_JURNAL_DTL
ALTER TABLE ACCT_JURNAL_DTL ADD (
    CREATED_DATE   TIMESTAMP DEFAULT SYSTIMESTAMP,
    MODIFIED_DATE  TIMESTAMP
);

UPDATE ACCT_JURNAL_DTL SET CREATED_DATE = SYSTIMESTAMP WHERE CREATED_DATE IS NULL;
COMMIT;

-- 3. Create ACCT_JURNAL_AUDIT table for UPDATE/DELETE history
CREATE TABLE ACCT_JURNAL_AUDIT (
    AUDIT_ID       NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    JURNALID       NUMBER NOT NULL,
    ACTION_TYPE    VARCHAR2(20) NOT NULL,   -- UPDATE, DELETE
    ACTION_DATE    TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    ACTION_BY      VARCHAR2(50) NOT NULL,
    ACTION_PC      VARCHAR2(100),
    ACTION_IP      VARCHAR2(50),
    -- Snapshot of header state at time of action
    NOJURNAL       VARCHAR2(30),
    TANGGAL        DATE,
    PERIODE        VARCHAR2(7),
    SUMBER         VARCHAR2(10),
    IDDATA         VARCHAR2(20),
    -- For UPDATE: what changed
    CHANGED_FIELDS VARCHAR2(1000),
    -- For DELETE: reason
    DELETE_REASON  VARCHAR2(200),
    -- Detail changes summary
    DETAIL_ROWS_INSERTED  NUMBER DEFAULT 0,
    DETAIL_ROWS_UPDATED   NUMBER DEFAULT 0,
    DETAIL_ROWS_DELETED   NUMBER DEFAULT 0
);

-- 4. Create ACCT_JURNAL_AUDIT_DTL table for detail-level audit trail
CREATE TABLE ACCT_JURNAL_AUDIT_DTL (
    AUDIT_DTL_ID   NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    AUDIT_ID       NUMBER NOT NULL,          -- FK to ACCT_JURNAL_AUDIT
    CHANGE_TYPE    VARCHAR2(10) NOT NULL,     -- ADDED, MODIFIED, DELETED, SNAPSHOT
    BARIS          NUMBER,
    KODE           VARCHAR2(20),
    REKENING       VARCHAR2(200),
    DEBET          NUMBER(18,2),
    KREDIT         NUMBER(18,2),
    KETERANGAN     VARCHAR2(200),
    -- Old values for MODIFIED rows (NULL for ADDED/SNAPSHOT)
    OLD_KODE       VARCHAR2(20),
    OLD_DEBET      NUMBER(18,2),
    OLD_KREDIT     NUMBER(18,2),
    OLD_KETERANGAN VARCHAR2(200),
    CONSTRAINT FK_AUDIT_DTL_HDR FOREIGN KEY (AUDIT_ID) REFERENCES ACCT_JURNAL_AUDIT (AUDIT_ID)
);

-- 5. Indexes for audit queries
CREATE INDEX IDX_AUDIT_JURNALID ON ACCT_JURNAL_AUDIT (JURNALID);
CREATE INDEX IDX_AUDIT_ACTION_DATE ON ACCT_JURNAL_AUDIT (ACTION_DATE);
CREATE INDEX IDX_AUDIT_ACTION_BY ON ACCT_JURNAL_AUDIT (ACTION_BY);
CREATE INDEX IDX_AUDIT_IDDATA ON ACCT_JURNAL_AUDIT (IDDATA);
CREATE INDEX IDX_AUDIT_DTL_AUDIT_ID ON ACCT_JURNAL_AUDIT_DTL (AUDIT_ID);
